# Generated by Django 5.1.10 on 2025-07-02 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0029_datasetversion_versiontask"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="active_version",
            field=models.ForeignKey(
                blank=True,
                help_text="Active dataset version for labeling",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="active_for_project",
                to="projects.datasetversion",
            ),
        ),
    ]
