# Generated by Django 5.1.10 on 2025-07-07 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0030_project_active_version"),
        ("tasks", "0055_task_proj_octlen_idx_async"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetversion",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Created"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="created",
                max_length=64,
                verbose_name="status",
            ),
        ),
        migrations.CreateModel(
            name="ProcessedTask",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("processed_data", models.FileField(upload_to="processed_tasks/")),
                ("processed_annotations", models.JSONField(default=dict)),
                (
                    "original_task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processed_tasks",
                        to="tasks.task",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processed_tasks",
                        to="projects.datasetversion",
                    ),
                ),
            ],
        ),
    ]
