# Generated by Django 5.1.10 on 2025-09-06 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_add_pachyderm_fields"),
        ("projects", "0031_datasetversion_status_processedtask"),
    ]

    operations = []
