# Generated by Django 5.1.10 on 2025-10-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0033_add_dataset_export"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasetversion",
            name="augmentation_multiplier",
            field=models.IntegerField(
                default=1, help_text="Augmentation multiplier for training set (1-5)"
            ),
        ),
    ]
