# Generated by Django 5.1.10 on 2025-10-18 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0034_datasetversion_augmentation_multiplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="pachyderm_config",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Pachyderm connection configuration (host, port, auth_token, tls)",
            ),
        ),
    ]
